# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
    MercenariesProcessReviewQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: mercenaries-process-match-queue
            VisibilityTimeout: 601
    MercenariesProcessReviewSqsQueuePolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
            PolicyDocument:
                Version: '2012-10-17'
                Id: MercenariesProcessReviewQueuePolicy
                Statement:
                    - Sid: Allow-SNS-SendMessage
                      Effect: Allow
                      Principal:
                          AWS: '*'
                      Action:
                          - sqs:SendMessage
                      Resource: !GetAtt MercenariesProcessReviewQueue.Arn
                      Condition:
                          ArnEquals:
                              aws:SourceArn: arn:aws:sns:us-west-2:478062583808:mercenaries-review-published
            Queues:
                - !Ref MercenariesProcessReviewQueue
    SnsSubscription:
        Type: AWS::SNS::Subscription
        Properties:
            Protocol: SQS
            Endpoint: !GetAtt MercenariesProcessReviewQueue.Arn
            TopicArn: arn:aws:sns:us-west-2:478062583808:mercenaries-review-published

    ProcessMercenariesReviewFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: process-mercenaries-review.default
            Runtime: nodejs12.x
            CodeUri: ./dist/process-mercenaries-review
            MemorySize: 256
            Timeout: 40
            ReservedConcurrentExecutions: 15
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - SecretsManagerReadWrite
                - AmazonSESFullAccess
                - AmazonSQSFullAccess
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: process-mercenaries-review
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt MercenariesProcessReviewQueue.Arn
